booking/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'booking'

urlpatterns = [
    path('users/', include('users.urls')),
    path('users/profile/<int:pk>/booking/', views.BookingView.as_view(), name='user_booking_new'),
    path('booking/', views.BookingListView.as_view(), name="booking_list"),
    path('booking/<int:pk>/', views.BookingDetailView.as_view(), name="booking_detail"),
    path('booking/edit/<int:pk>/', views.BookingUpdateView.as_view(), name="booking_update"),
    path('booking/delete/<int:pk>/', views.BookingDeleteView.as_view(), name="booking_delete"),
    path('booking/confirm/<int:pk>', views.ConfirmView.as_view(), name='confirm_booking'),
#    path('users/profile/<int:pk>/booking/<int:pk>/', views.BookingDetailView.as_view(), name="booking_detail"),
#    path('users/profile/<int:pk>/booking/edit/<int:pk>/', views.BookingUpdateView.as_view(), name="booking_update"),
#    path('booking/edit/<int:pk>/booking/delete/<int:pk>/', views.BookingDeleteView.as_view(), name="booking_delete"),
 
 
]



    #path('users/profile/booking/', views.CalendarView.as_view(), name='calendar'),
    #path('booking/calendar/', views.calendar, name='new_calendar'),

pages/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
   
]

scipertise_demo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404


urlpatterns = [
 
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('search/', include('search.urls', namespace='search')),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('', include('booking.urls', namespace='booking')),
    

  
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'pages.views.error_404_view'

booking/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.urls import reverse
from users.models import CustomUser

 

# Create your models here.

class Booking(models.Model):
    user = models.ForeignKey(CustomUser, null=True, default='', on_delete=models.CASCADE)
    expert = models.ForeignKey(CustomUser, null=True, default='',on_delete=models.CASCADE, related_name='bookings')
    title = models.CharField(max_length=200, default='Title/subject of your video call', null=True)
    start_time = models.DateTimeField('Start time', null=True)
    end_time = models.DateTimeField('End time', null=True)
    notes = models.TextField('Notes', blank=True, null=True) 
    is_confirmed = models.BooleanField(blank=True, default=False)
    is_tutorial = models.BooleanField(blank=True, default=False)
    description = models.TextField('Description', blank=True, null=True) 
  
 
    class Meta:
        verbose_name = 'Booking'
        verbose_name_plural = 'Bookings'
        
    def get_absolute_url(self):
        return reverse('booking:booking_detail', kwargs={"pk": self.pk})
    
#class Confirmation(models.Model):
#    booking = models.ForeignKey(Booking, on_delete=models.CASCADE)
#    expert_confirming = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
#    is_confirmed = models.BooleanField(default=False)
#    
#    def get_absolute_url(self):
#        return reverse('booking:booking_detail', kwargs={"pk": self.booking_id})
#    

booking/forms.py
from django.forms import ModelForm, DateInput
from booking.models import Booking
from django import forms
from bootstrap_datepicker_plus import DatePickerInput, TimePickerInput, DateTimePickerInput, MonthPickerInput, YearPickerInput


        
class BookingForm(ModelForm):
    class Meta:
        model = Booking
        fields = ['title','start_time','end_time','notes']
        # datetime-local is a HTML5 input type, format to make date time show on fields
        labels = {
          'title': 'Please select a title for your requested video call:',
          'start_time': 'Suggested date and start time:',
          'end_time': 'Suggested end time:',
          'notes': 'Describe what you are interested in discussing in 2-3 sentences:',
        }
        widgets = {
          'title': forms.TextInput(attrs={'class': 'form-control'}),
          'start_time': DateTimePickerInput(format="YYYY-MM-DD HH:mm"),
          'end_time': DateTimePickerInput(format="YYYY-MM-DD HH:mm"),
          'notes': forms.Textarea(attrs={'class': 'form-control'}),
        }
        help_texts = {
    
          'start_time': 'Please select a date and time during the available hours listed on the expert profile page',
          'end_time': '*Appointments cannot exceed 1 hour'
          
        }



class ConfirmForm(ModelForm):
    class Meta:
        model = Booking
        fields = ['is_confirmed']
        # datetime-local is a HTML5 input type, format to make date time show on fields
        labels = {
          'is_confirmed': 'I confirm this video call',
        }
        

booking/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views import generic
from django.views.generic import CreateView, TemplateView, DetailView, ListView, UpdateView, DeleteView
from django.http import HttpResponseRedirect
from datetime import datetime
from django.http import HttpResponse
from django.utils.safestring import mark_safe
from datetime import datetime, timedelta
from calendar import HTMLCalendar
import calendar
from django.core.mail import send_mail

from users.forms import CustomUserCreationForm, EditProfile
from users.models import CustomUser
#from booking.utils import Calendar
from booking.models import Booking
from booking.forms import BookingForm, ConfirmForm

from django.template.loader import render_to_string
from django.utils.html import strip_tags


class BookingView(CreateView):
    model = Booking
    form_class = BookingForm
    def form_valid(self, form):
        booking = form.save(commit=False)
        form.instance.user = self.request.user
        form.instance.expert = CustomUser.objects.get(id=self.kwargs.get('pk'))
#        user_email = form.instance.user.email
#        expert_email = form.instance.expert.email
#
#        html_message = render_to_string('booking_request_email_user.html', {'user': form.instance.user,
#                                                                            'expert': form.instance.expert})
#        html_message_expert = render_to_string('booking_request_email_expert.html', {'user': form.instance.user,
#                                                                            'expert': form.instance.expert,
#                                                                            'booking': booking,
#                                                                            })
#        plain_message = strip_tags(html_message)
#        plain_message_expert = strip_tags(html_message_expert)
#    #send email to the user
#        send_mail('Thanks for your booking request ' + form.instance.user.first_name, plain_message, 'founders@scipertise.com', [user_email], fail_silently=False, html_message=html_message)
#    #send email to the expert
#        send_mail(form.instance.user.first_name + " has requested a video call with you", plain_message_expert, 'founders@scipertise.com', [expert_email], fail_silently=False, html_message=html_message_expert)
        return super(BookingView, self).form_valid(form)

    
class BookingUpdateView(UpdateView):
    model = Booking
    form_class = BookingForm
    def form_valid(self, form):
        booking = Booking.objects.get(id=self.kwargs.get('pk'))
        form.instance.user = booking.user
        form.instance.expert = booking.expert
#        user_email = form.instance.user.email
#        expert_email = form.instance.expert.email
#        html_message = render_to_string('update_booking_user.html', {'user': form.instance.user,
#                                                                            'expert': form.instance.expert,
#                                                                            'booking': booking,
#                                                                            })
#        html_message_expert = render_to_string('update_booking_expert.html', {'user': form.instance.user,
#                                                                            'expert': form.instance.expert,
#                                                                            'booking': booking,
#                                                                            })
#        plain_message = strip_tags(html_message)
#        plain_message_expert = strip_tags(html_message_expert)
#    #send email to the user
#        send_mail('Your Scipertise booking request has been changed', plain_message, 'founders@scipertise.com', [user_email], fail_silently=False, html_message=html_message)
#    #send email to the expert
#        send_mail('Your Scipertise booking request has been changed', plain_message_expert, 'founders@scipertise.com', [expert_email], fail_silently=False, html_message=html_message_expert)
        return super(BookingUpdateView, self).form_valid(form)

    
class BookingDeleteView(DeleteView):
    model = Booking
    success_url = reverse_lazy('profile')
    def form_valid(self, form):
        booking = Booking.objects.get(id=self.kwargs.get('pk'))
        form.instance.user = booking.user
        form.instance.expert = booking.expert
#        user_email = form.instance.user.email
#        expert_email = form.instance.expert.email
#        html_message = render_to_string('delete_booking_user.html', {'user': form.instance.user,
#                                                                            'expert': form.instance.expert,
#                                                                            'booking': booking,
#                                                                            })
#        html_message_expert = render_to_string('delete_booking_expert.html', {'user': form.instance.user,
#                                                                            'expert': form.instance.expert,
#                                                                            'booking': booking,
#                                                                            })
#        plain_message = strip_tags(html_message)
#        plain_message_expert = strip_tags(html_message_expert)
#    #send email to the user
#        send_mail('Your Scipertise booking has been cancelled', plain_message, 'founders@scipertise.com', [user_email], fail_silently=False, html_message=html_message)
#    #send email to the expert
#        send_mail('Your Scipertise booking has been cancelled', plain_message_expert, 'founders@scipertise.com', [expert_email], fail_silently=False, html_message=html_message_expert)
        return super(BookingUpdateView, self).form_valid(form)

class BookingListView(ListView):
    model = Booking
    context_object_name = 'booking_list'
    template = 'templates/booking_list.html'
    
    def get_queryset(self):
        bookings = Booking.objects.filter(user=self.request.user)
        return bookings

    
class BookingDetailView(DetailView):
    model = Booking
    template = 'templates/booking_detail.html'
    
class ConfirmView(UpdateView):
    model = Booking
    form_class = ConfirmForm
    template = 'templates/confirmation_form.html'
#    def form_valid(self, form):
#        booking = Booking.objects.get(id=self.kwargs.get('pk'))
#        form.instance.user = booking.user
#        form.instance.expert = booking.expert
#        user_email = form.instance.user.email
#        expert_email = form.instance.expert.email
#        html_message = render_to_string('confirm_booking_user.html', {'user': form.instance.user,
#                                                                            'expert': form.instance.expert,
#                                                                            'booking': booking,
#                                                                            })
#        html_message_expert = render_to_string('confirm_booking_expert.html', {'user': form.instance.user,
#                                                                            'expert': form.instance.expert,
#                                                                            'booking': booking,
#                                                                            })
#        plain_message = strip_tags(html_message)
#        plain_message_expert = strip_tags(html_message_expert)
#    #send email to the user
#        send_mail('Your Scipertise booking has been confirmed', plain_message, 'founders@scipertise.com', [user_email], fail_silently=False, html_message=html_message)
#    #send email to the expert
#        send_mail('Your Scipertise booking has been confirmed', plain_message_expert, 'founders@scipertise.com', [expert_email], fail_silently=False, html_message=html_message_expert)
#        return super(ConfirmView, self).form_valid(form)
    
#@login_required
#def EditProfileView(request):
#    form = EditProfile()
#    if request.method == 'POST':
#        form = EditProfile(request.POST, instance =request.user)
#        if form.is_valid():
#            form.save()
#        return HttpResponseRedirect(reverse('profile'))
#    else:
#        form = EditProfile(instance = request.user)
#        return render(request, 'edit_profile.html', {'form': form})

#class CalendarView(generic.ListView):
#    model = Booking
#    template_name = 'calendar.html'
#    
#    
#    def get_context_data(self, **kwargs):
#        context = super().get_context_data()
#
#
#        # use today's date for the calendar
#        d = get_date(self.request.GET.get('day', None))
#      
#        # Instantiate our calendar class with today's year and date
#        cal = Calendar(d.year, d.month)
#
#        # Call the formatmonth method, which returns our calendar as a table
#        html_cal = cal.formatmonth(withyear=True)
#        context['calendar'] = mark_safe(html_cal)
#        d = get_date(self.request.GET.get('month', None))
#        context['prev_month'] = prev_month(d)
#        context['next_month'] = next_month(d)
#      
#        return context
#    
#
#    
#def get_date(req_day):
#    if req_day:
#        year, month = (int(x) for x in req_day.split('-'))
#        return date(year, month, day=1)
#    return datetime.today()
#        
#
#def prev_month(d):
#    first = d.replace(day=1)
#    prev_month = first - timedelta(days=1)
#    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
#    return month
#
#def next_month(d):
#    days_in_month = calendar.monthrange(d.year, d.month)[1]
#    last = d.replace(day=days_in_month)
#    next_month = last + timedelta(days=1)
#    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
#    return month

#

booking/templates/booking/booking_confirm_delete.html
{% extends 'layout.html' %}
{% load static %}

<h1>Bookings</h1>

{% block content %}
<div class="container-fluid booking">
<div class="container" id="profile_content">
   <div class="container" id="booking_form_text"><h3>Delete {{ booking.title }}?</h3></div>
<div class="container delete_booking">
    <form  method ="POST">
    {% csrf_token %}
   <button type='submit' class='btn btn-danger' value="Delete">Delete Booking</button>
    </form> 
    <a href="{% url 'booking:booking_list' %}">Cancel</a>
    </div>


</div>
    </div>

{% endblock %}

booking/templates/booking/booking_detail.html
{% extends 'layout.html' %}
{% load static %}

<h1>Bookings</h1>

{% block content %}

<div class="container-fluid booking">
    <div class="container" id="booking_detail_text"><h3>Booking details</h3></div>
    <div class="container" id="booking_content">
        <div class="container card">
        <div class="container confirmed">
        <h3 class="card-title">{{ booking.title }}&nbsp&nbsp</h3>
        {% if booking.is_confirmed %}
      <p class="confirmed">This booking is confirmed.&nbsp&nbsp</p><img class="check" src="/static/css/check.svg">
        {% else %}
        <p class="confirmed">This booking has not yet been confirmed by the requested expert. You will receive an email upon confirmation.&nbsp&nbsp<img class="x" src="/static/css/warning.svg"></p>
        {% endif %}
            
            </div>    
       <div class="container">
        <p>{{ booking.start_time }}</p>
        <p>Booking made by: {{ booking.user }}</p>
        <p>Scipertise Researcher: {{ booking.expert }}</p>
        {% if booking.is_tutorial %}
            <p>This booking is a group session limited to 5 people</p>
            <p><strong>Description: </strong>{{ booking.description }}</p>
           <p> Please contact founders@scipertise.com to see if there are any spaces remaining.</p>
        {% endif %}  
            
    </div>

    </div>

{% if not booking.is_confirmed and user.expert and booking.expert == request.user %}
  <div><a href="{% url 'booking:confirm_booking' pk=booking.pk %}"><button type='submit' class='booking_button'>Confirm Booking Request</button></a></div> 
{% endif %}
  <div><a href="{% url 'booking:booking_update' pk=booking.pk %}"><button type='submit' class='booking_button'>Edit Booking Request</button></a></div> 
   <div><a href="{% url 'booking:booking_delete' pk=booking.pk %}"><button type='submit' class='booking_button'>Delete Booking</button></a></div> 
    </div>
  
</div>



{% endblock %}

booking/templates/booking/booking_form.html
{% extends 'layout.html' %}
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{{ form.media }} 
{% load widget_tweaks %}

{% block title %}
Event
{% endblock %}

{% block content %}

<div class="container-fluid booking">
    {% if booking and booking.is_confirmed == False and booking.user == request.user %}
    <div class="container" id="booking_form_text"><h3>Please select a new time for your video call</h3></div>
    {% elif booking and booking.is_confirmed == False and booking.expert == request.user %}
     <div class="container" id="booking_form_text"><h3>Please confirm booking request</h3></div>
    {% elif booking %}
    <div class="container" id="booking_form_text"><h3>Please select a new time for your video call</h3></div>
    {% else %}
    <div class="container" id="booking_form_text"><h3>Please select a time for your video call</h3></div>
     {% endif %}
    <div class="container" id="booking_form">
       
 
        
    <form method="post">
      {% csrf_token %}

    <div class="form-group booking_form">
     {% for field in form.visible_fields %}
      {{ field.label_tag }}
      {% render_field field class="form-control" %}
      {% if field.help_text %}
    <small class="form-text text-muted">{{ field.help_text |safe }}</small>
      {% endif %}
    {% endfor %}
    <button type="submit" class="availability_button">Submit</button><br><br>
    
  </div>
</form>
        
        
        
        
        
<!--
        
    <form method="post" class="booking_form">
      {% csrf_token %}

        {{ form.as_p }}

    <button type="submit" class="availability_button"> Request to Book </button>

    </form>
-->
    </div>
</div>


{% endblock %}

booking/templates/booking/booking_list.html
{% extends 'layout.html' %}
{% load static %}


{% block content %}
<div class="container-fluid booking">



<div class='container booking_list'>
{% if user.bookings.all or user.booking_set.all %}
<div class="container" id="booking_form_text"><h3>Your scheduled video sessions:</h3></div>
   
{% for booking in user.bookings.all %}
    <div class="container card booking_list">
        <h5 class="card-title"><a href="{% url 'booking:booking_detail' pk=booking.pk %}">{{ booking.title }}</a></h5>
        <p class="card-text">Session with {{ booking.user }} on {{booking.start_time}}</p>
    </div>
    
{% endfor %}
{% for booking in user.booking_set.all %}
    
       <div class="container card booking_list">
        <h5 class="card-title"><a href="{% url 'booking:booking_detail' pk=booking.pk %}">{{ booking.title }}</a></h5>
        <p class="card-text">Session with {{ booking.user }} on {{booking.start_time}}</p>
    </div>
{% endfor %}
    
</div>


{% else %} 

<div class="container" id="booking_form_text"><h3>You have no scheduled video sessions.</h3></div>
   

{% endif %}
    </div>




{% endblock %}

booking/templates/booking/confirmation_form.html
{% extends 'layout.html' %}
{% load static %}
{% load widget_tweaks %}

<h1>Bookings</h1>

{% block content %}

<div class="container-fluid booking">
    <div class="container" id="booking_form_text"><h3>Booking request confirmation</h3></div>
    <div class="container" id="booking_content">
        
    <form method="post">
      {% csrf_token %}

    <div class="form-group booking_form">
     {% for field in form.visible_fields %}
      {{ field.label_tag }}
      {% render_field field class="form-control" %}<br>
      {% if field.help_text %}
    <small class="form-text text-muted">{{ field.help_text |safe }}</small>
      {% endif %}
    {% endfor %}
    <button type="submit" class="availability_button">Yes I Confirm</button>
    </div>
  
</form>
    </div>

</div>



{% endblock %}