booking/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'booking'

urlpatterns = [
    path('users/', include('users.urls')),
    path('users/profile/<int:pk>/booking/', views.BookingView.as_view(), name='user_booking_new'),
    path('booking/', views.BookingListView.as_view(), name="booking_list"),
    path('booking/<int:pk>/', views.BookingDetailView.as_view(), name="booking_detail"),
    path('booking/edit/<int:pk>/', views.BookingUpdateView.as_view(), name="booking_update"),
    path('booking/delete/<int:pk>/', views.BookingDeleteView.as_view(), name="booking_delete"),
    path('booking/confirm/<int:pk>', views.ConfirmView.as_view(), name='confirm_booking'),
#    path('users/profile/<int:pk>/booking/<int:pk>/', views.BookingDetailView.as_view(), name="booking_detail"),
#    path('users/profile/<int:pk>/booking/edit/<int:pk>/', views.BookingUpdateView.as_view(), name="booking_update"),
#    path('booking/edit/<int:pk>/booking/delete/<int:pk>/', views.BookingDeleteView.as_view(), name="booking_delete"),
 
 
]



    #path('users/profile/booking/', views.CalendarView.as_view(), name='calendar'),
    #path('booking/calendar/', views.calendar, name='new_calendar'),

pages/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
   
]

scipertise_demo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404


urlpatterns = [
 
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('search/', include('search.urls', namespace='search')),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('', include('booking.urls', namespace='booking')),
    

  
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'pages.views.error_404_view'

search/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import search_users


app_name = 'search'

urlpatterns = [
    path('', search_users, name='search_users'),
    path('users/', include('users.urls')),

   
 
] 

search/models.py
from django.db import models

# Create your models here.

search/views.py
from django.shortcuts import render
from django.db.models import Q
from users.models import CustomUser
from django.views.generic import TemplateView, DetailView, ListView
from users.models import CustomUser
from taggit.models import Tag
from functools import reduce

# Create your views here.

def search_users(request):
    if request.method == 'GET':
        query= request.GET.get('q')
        submitbutton= request.GET.get('submit')
        if query is not None:
            lookups = Q(skills__name__icontains=query) | Q(software_hardware__icontains=query)
            results = CustomUser.objects.filter(lookups).distinct()
            context={'results': results, 'submitbutton': submitbutton}
            return render(request, 'search.html', context)
        else:
            return render(request, 'search.html')
    else:
        return render(request, 'search.html')



 

templates/booking_request_email_expert.html
<h4>Hi {{ expert.first_name }}, </h4>

<p>{{ user.first_name }} has requested a video call with you for {{ booking.start_time }} The title of the booking is {{ booking.title }}.<br>Here is a short description of what they would like to discuss: {{ booking.notes }}<br> Please login <a href="www.scipertise.com">here</a>, select "My Schedule" and click on the booking to confirm.</p>
<p>Sincerely,</p>
<p>The Scipertise Team</p>

templates/change_password.html
{% extends 'layout.html' %}
{% load static %}
{% load widget_tweaks %}


{% block title %}Change Password{% endblock %}

{% block content %}

<div class="container-fluid" id="change_password">

<div class="container" id="edit_profile">

<!--
<form class="signup_form" action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
     <button type="submit" class="btn btn-primary">Save Changes</button>
    </form>
-->
    
    
<form method="post">
      {% csrf_token %}

    <div class="form-group">
     {% for field in form.visible_fields %}
     {{ field.errors }}
      {{ field.label_tag }}
      {% render_field field class="form-control" %}
      {% if field.help_text %}
    <small class="form-text text-muted">{{ field.help_text |safe }}</small>
      {% endif %}
    {% endfor %}
    </div>
  <button type="submit" class="availability_button">Save Changes</button>
</form>
               
</div>
    </div>


{% endblock %}
        

templates/confirm_booking_expert.html
<h4>Hi {{ expert.first_name }}, </h4>

<p>Thanks for confirming your booking with {{ user.first_name }} for {{ booking.start_time }}<br> 
You will receive a reminder email and link to the video conference prior to your call.</p>
<p>Sincerely,</p>
<p>The Scipertise Team</p>

templates/confirm_booking_user.html
<h4>Hi {{ user.first_name }}, </h4>

<p>{{ expert.first_name }} has confirmed your booking request for {{ booking.start_time }}</p>
<p>You will receive a reminder email and link to the video conference prior to your call.</p>
<p>Sincerely,</p>
<p>The Scipertise Team</p>

templates/custom_404.html
{% load static %}

<html>
<head>
     <link rel="stylesheet" href="{% static '/css/layout.css' %}">
  
    <link href="https://fonts.googleapis.com/css?family=Montserrat|PT+Sans" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet"> 
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic-bootstrap.min.css" integrity="sha256-BJ/G+e+y7bQdrYkS2RBTyNfBHpA9IuGaPmf9htub5MQ=" crossorigin="anonymous" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.js"></script> 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="iconic.min.js"></script>
    </head>
<div class="container jumbotron">
    	<h1>oops!</h1>
			<h2>Error 404 : Page Not Found</h2>
			<a href="{% url 'home' %}">Go back to the homepage</a>
    </div>
</html>

templates/delete_booking_expert.html
<h4>Hi {{ expert.first_name }}, </h4>

<p>Your video call titled {{ booking.title }}, requested by {{ user.first_name }} has been cancelled. Thank you for using Scipertise.</p>
<p>Sincerely,</p>
<p>The Scipertise Team</p>

templates/delete_booking_user.html
<h4>Hi {{ user.first_name }}, </h4>

<p>Your video call titled {{ booking.title }}, with {{ expert.first_name }} has been cancelled. Thank you for using Scipertise.</p>
<p>Sincerely,</p>
<p>The Scipertise Team</p>

templates/edit_profile.html
{% extends 'layout.html' %}
{% load static %}
{% load widget_tweaks %}
{% block title %}Edit Profile{% endblock %}

{% block content %}


<div class="container-fluid" id="login">

<div class="container" id="edit_profile">
    
    
    
<form class ="signup_form" method="post">
      {% csrf_token %}

    <div class="form-group booking_form">
     {% for field in form.visible_fields %}
      {{ field.label_tag }}
      {% render_field field class="form-control" %}
      {% if field.help_text %}
    <small class="form-text text-muted">{{ field.help_text |safe }}</small>
      {% endif %}
    {% endfor %}
     <a href="{% url 'change_password' %}"><p>Change Password</p></a>
     <button type="submit" class="btn btn-primary">Save Changes</button>
    
  </div>
</form>
        
        
               
</div>
</div>


{% endblock %}

templates/home.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}Home{% endblock %}

{% block content %}

        
        <div class="container-fluid" id ="first_section_row">

                <div class="container" id="vision">
                <div class ="container" id="vision_text">
                    <h1 class="value_prop">Solve your research problems faster</h1>
                    <p class="vision_blurb">Connect with a researcher who has the expertise you need.<br>Sign up for Scipertise and do better research, faster.</p>
                    <p class="advice_blurb">Get insights on: <br> experimental models  |  software  |  lab techniques  |  equipment  |   data analysis</p>
                </div>


                </div>
                <div class = "container" id="call_to_action">
                    <form>
                        {% if user.is_authenticated %}
                        <a href="{% url 'search:search_users' %}"><button type="button" class="btn btn-primary" id ="call_to_action">Find Expertise</button></a>
                        {% else %}
                        <a href="{% url 'signup' %}"><button type="button" class="btn btn-primary" id ="call_to_action">Signup for beta</button></a>
                        {% endif %}
                    </form>
                </div>

            </div>
                <div class="container-fluid" id="second_section_row">

               
                 <div class=divtitle>
                    <h1>How it works</h1>
                </div>
               <div class="container-fluid" id="howitworks">
                <div class="container" id="step1" >
                
                
                    <img class="icon1" src="/static/css/scipertise_icon_step1.png">
                     
                        <h4 class ="icon_title">Find a Scientist</h4>
                        <p class="icontext">Browse researcher profiles or search for an expert by skill. Message someone to see if they're the right fit.</p>
               
                      
                </div>
                
                <div class="container" id="step2" >
                  
                    <img class="icon2" src="/static/css/scipertise_icon_step2.png">
                     
                        <h4 class ="icon_title">Book a Call</h4>
                        <p class="icontext">Schedule a video call with an expert of your choice. Get quick advice, help troubleshooting, or book a tutorial.</p>   
                </div>
                
                <div class="container" id="step3" >
                
                    <img class="icon3" src="/static/css/scipertise_icon_step3.png">
                        <h4 class ="icon_title">Solve Problems</h4>
                        <p class="icontext">Discuss, learn and solve problems with someone who has the right expertise. Move your research forward.</p>
                 
                    
                    
                </div>

            </div>
         </div>
            
               
        <div class="container-fluid" id ="third_section_row">
            <div class="container" id="section3_signup" > 
                <h2 class="section3_text">Scipertise is making it easier to find the expertise you need to improve your research. Join the movement and unlock your research potential.</h2>
            <a href="{% url 'signup' %}"><button type="button" class="btn btn-primary" id ="call_to_action">Signup for free beta access</button></a>
           
            </div>

          
</div>

   

{% endblock %}

templates/layout.html
{% load static %}
{% load bootstrap4 %}       {# imports bootstrap3 #}
{% bootstrap_css %}         {# Embeds Bootstrap CSS #}
{% bootstrap_javascript %}
{% bootstrap_javascript jquery='full' %} {# Embeds Bootstrap JS #}
{% block extrahead %} 
 {{ form.media }}          {# Embeds Extra Resources #}
{% endblock %}              {# Ends Extra Resources #}

<!doctype html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static '/css/layout.css' %}">
  
    <link href="https://fonts.googleapis.com/css?family=Montserrat|PT+Sans" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <!-- Latest compiled and minified CSS -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic-bootstrap.min.css" integrity="sha256-BJ/G+e+y7bQdrYkS2RBTyNfBHpA9IuGaPmf9htub5MQ=" crossorigin="anonymous" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.js"></script> 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    
 
    </head>
<body>  

<div class ="site-container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-left logo" href="{% url 'home' %}"><img class="logo" src="/static/css/brand.jpg"></a>
       <!-- <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button> -->
          <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                 <!-- <a class="nav-item nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a> -->
                  {% if user.is_authenticated %}
                
                 <form class="form-inline my-2 my-lg-0" action="{% url 'search:search_users' %}" method="GET" value="{{request.GET.q}}">
                  <input class="form-control mr-sm-2" type="text" name="q" value="{{request.GET.q}}" placeholder="Search by Skill">
                  <button class="btn btn-primary my-2 my-sm-0" id = "search" name="submit" type="submit" value ="Search">Search</button>
                </form>
                
                
                <a class="nav-item nav-link" href="{% url 'browse' %}">Browse</a>
                {% if user.expert == True %}
                  <a class="nav-item nav-link" href="{% url 'profile' %}">My Profile</a>
                {% endif %}
                  <a class="nav-item nav-link" href="{% url 'booking:booking_list' %}">My Schedule</a>
                  <a class ="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                  {% else %}
                  <form class="form-inline my-2 my-lg-0">
                    <a  href="{% url 'signup' %}"><button class="btn btn-primary" type="button">Signup for FREE</button></a>
                  </form>
                  <a class ="nav-item nav-link" id="login" href="{% url 'login' %}">Log In</a>
                  {% endif %}
            </div>
          </div>
    </nav>

        
  <!--  {% if messages %}
       <div class ="row">
       {% for message in messages %}
           <div data-alert class="alert-box {{ message.tags }} radius"></div>
            {{ message }}
           <a href="#" class ="close">&times;</a>
       </div>
       {% endfor %}
       {% endif %} -->
        
        
    {% block content %}{% endblock %}
    </div> 
    </body>

templates/search.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}Search{% endblock %}

{% block content %}

<div class="container-fluid search">
    <div class="container" id="search_form">
            <form class="form-group" action="{% url 'search:search_users' %}" method="GET" value="{{request.GET.q}}">
            <h3 id="search_call_to_action">Find researchers</h3>
                <input class="form-control form-control-lg" id="search" type="text" name="q" value="{{request.GET.q}}" placeholder="Enter a skill, technique, software or area of expertise"/>
                <button class="availability_button" type="submit" name="submit" value="Search">Search</button>
            </form>
        </div>

        {% if submitbutton == 'Search' and request.GET.q != '' %}
        {% if results %}
        
        <div class="container" id="search_results">
        <h3>Researchers Matching "<b>{{ request.GET.q }}</b>"</h3>
        <br/><br/>

        {% for result in results %}

        <div class="container" id="search_hit">
        <div class="container" id="expert">
            {% if result.image %}
            <div>
                <img class="profile_image" src="{{ result.image.url }}" width="100"/>
            </div>
            {% endif %}
            <div class="container user_name">
            <p class="profile_name"><a href="{% url 'profile_with_pk' pk=result.pk %}">{{ result.first_name }}&nbsp{{ result.last_name }}</a></p>
            <p class="profile_text">{{result.position}}</p>
<!--            <p class="profile_text">Skills:&nbsp{{user.skills.all|join:", "}}</p>-->
        
                
                <div class="container skills">
                {% for skill in result.skills.all %}
                <div class="skill_bubble"><p class="skill_bubble">{{ skill.name }}</p></div>
                    {% endfor %}
                
                </div>
                 <div class="browse_bio"> {{result.bio }}</div>
            </div>

        </div>
        </div>



        {% endfor %}
        {% else %}
       <div class="container"><p class="profile_text">No search results for this query.<br>Please try searching for a specific skill, software, or area of expertise.</p></div> 
        {% endif %}
        {% endif %}

        {% endblock %}
    </div>
    
</div>

templates/signup.html
{% extends 'layout.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}Sign Up{% endblock %}

{% block content %}


<div class="container-fluid" id="signup">
    <div class="signup_bgrd">
        


 <h2>Sign up for a free account and access our beta</h2>
 {% if form.errors %}
        <br>
<p>There was an error. Please try again.</p>
{% endif %}               
<form method="post">
      {% csrf_token %}

    <div class="form-group">
     {% for field in form.visible_fields %}
     {{ field.errors }}
      {{ field.label_tag }}
      {% render_field field class="form-control" %}
      {% if field.help_text %}
    <small class="form-text text-muted">{{ field.help_text |safe }}</small>
      {% endif %}
    {% endfor %}
    </div>
  <button type="submit" class="availability_button">Sign Up</button>
</form>
        
        
        
        
        
<!--
        
            <h4>Sign up for a free account</h4>
         <form class="signup_form" action="" method="POST">
             {% csrf_token %}
             {{ form.as_p }}
                <p class="form_text" label="First Name">First Name:</p>
                 {{ form.first_name }}
                <p class="form_text" label="Last Name">Last Name:</p>
                 {{ form.last_name }}
                <p class="form_text" label="Email">Email:</p>
                 {{ form.email  }}
                <p class="form_text" label="Password">Password:</p>
                 {{ form.password1 }}
                 <br>     
      <button type="submit" class="btn btn-primary">Sign up</button>
               </form>
-->
    </div>


</div>



{% endblock %}

templates/update_booking_expert.html
<h4>Hi {{ expert.first_name }}, </h4>

<p>Your video call requested by {{ user.first_name }} has been modified. The new requested date and time is {{ booking.start_time }}. The title of the booking is {{ booking.title }}.<br>Here is a short description of what they would like to discuss: {{ booking.notes }}<br> Please login <a href="www.scipertise.com">here</a>, select "My Schedule" and click on the booking to confirm.</p>
<p>Sincerely,</p>
<p>The Scipertise Team</p>

templates/update_booking_user.html
<h4>Hi {{ user.first_name }}, </h4>

<p>Your booking request with {{ expert.first_name }} has been modified. The new requested date is {{ booking.start_time }}. You will receive an email when {{ expert.first_name }} has confirmed the booking time slot.</p>
<p>Sincerely,</p>
<p>The Scipertise Team</p>